### ISSUE TITLE
Let's use something more unixy for checking if branch exists in an array of IGNORED branches.

### ISSUE THREAD

**Issue by RobusGauli** [sbimochan/smart-commit#16]
This would replace this 
```

IS_IGNORED=false
	
for branch in "${IGNORED_BRANCHES[@]}";
    do
        if [ "$CURRENT_BRANCH" == $branch ]
        then
            IS_IGNORED=true
	    break
	fi
done
```

To
```
EXISTS=$(printf '%s\n' "${IGNORED_BRANCHES[@]}" | grep -x $CURRENT_BRANCH | wc -l)
```

This will return 0 if branch does not exists.
Finally we can do something like.
```
if [ $EXISTS = 0 ]
then
...
```

**Comment by sbimochan** [comment]
But it will be lil unreadable.

**Comment by aviskarkc10** [comment]
we can leave a comment above saying what it does.

**Comment by sbimochan** [comment]
what about ```if [[ -f "$IGNORED_PATH ]] && grep -qFx "$CURRENT_BRANCH" "$IGNORED_PATH"
then
  IS_IGNORED=true
fi```

**Comment by aviskarkc10** [comment]
if you directly read and check from the ignore file, you will miss out on the default ignored branches.

**Comment by sbimochan** [comment]
Right

**Comment by RobusGauli** [comment]
Best practices in bash is to wrap a statements into a function even if it is single line. so let's wrap this line inside a function like this. Reference from https://github.com/creationix/nvm/blob/master/nvm.sh
```
branch_exists() {
  echo $(printf '%s\n' "${IGNORED_BRANCHES[@]}" | grep -x $CURRENT_BRANCH | wc -l)
   
}
```

And write
```
if [ ${branch_exists) = 0 ] 
then 
...
```

What do you think @sbimochan @aviskarkc10 .

**Comment by RobusGauli** [comment]
> Best practices in bash is to wrap a statements inside a function even if it is single line. so let's wrap this line inside a function like this. Reference from https://github.com/creationix/nvm/blob/master/nvm.sh
> 
> ```
> branch_exists() {
>   echo $(printf '%s\n' "${IGNORED_BRANCHES[@]}" | grep -x $CURRENT_BRANCH | wc -l)
>    
> }
> ```
> And write
> 
> ```
> if [ ${branch_exists) = 0 ] 
> then 
> ...
> ```
> What do you think @sbimochan @aviskarkc10 .

**Comment by sbimochan** [comment]
@RobusGauli I just reverted wrapping up in function in #12 and merged it 😟

**Comment by RobusGauli** [comment]
😭 😢 I use this as a reference guide while bashing in shell. Let's follow this. 
[Best practices for Bash](https://github.com/progrium/bashstyle)

**Comment by sbimochan** [comment]
Sure man, now please stop crying.

**Comment by RobusGauli** [comment]
❤️ ❤️ ❤️ ❤️ ❤️  Only love . lol
